name: Fetch daily arXiv

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'  # Run this workflow every day at 00:05 UTC # it just need to run from Mon to Fri, not the best cron tho

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
     
    - name: Fetch XML data for all categories
      run: |
        python fetch_arxiv_categories.py

    - name: Commit and push
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Updated arxiv data"
        git push
