name: Fetch daily arXiv

on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'  

permissions:
  contents: write

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
     
    - name: Fetch XML data for all categories
      run: |
        python fetch_arxiv_feeds.py

    - name: Commit and push
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git add .
        # Check if there are any changes
        git diff --cached --quiet --exit-code || (git commit -m "Updated arxiv data" && git push)
